---
title: "Matthew McClellan's CV"
author: Matthew McClellan
date: "`r Sys.Date()`"
params:
  pdf_mode:
    value: true
output:
  pagedown::html_resume:
    css: ['dd_cv.css', 'resume']
    self_contained: true
---

```{r, include=FALSE}
knitr::opts_chunk$set(
  results='asis', 
  echo = FALSE
)

library(magrittr) # For the pipe
source("cv_printing_functions.r")

# Read in all data and initialize a CV printer object
CV <- create_CV_object(
  data_location = "https://docs.google.com/spreadsheets/d/1eiUSBQgD_B1wrqF0xWBKL7AytJAdS_VR0oDL91lckwg/edit#gid=917338460",  
  pdf_mode = params$pdf_mode
)

```


```{r}
# When in pdf export mode the little dots are unaligned, so fix that with some conditional CSS.
if(params$pdf_mode) {
    cat("
<style>
:root{
  --decorator-outer-offset-left: -6.5px;
}
</style>")
}
```


Aside
================================================================================
<!--
```{r}
# Build interactive network of positions colored by section
# and connected if they occurred in the same year
 datadrivencv::build_network_logo(CV$entries_data)
```
-->


```{r}
if(params$pdf_mode){
  cat("View this resume online with links at _matthewmcclellan.com/resume_")
} else {
  cat("[<i class='fas fa-download'></i> Download a PDF of this resume](https://github.com/mrmcclellan/cv/raw/master/mcclellan_resume.pdf)")
}
```


Contact {#contact}
--------------------------------------------------------------------------------

```{r}
CV %>% print_contact_info()
```


<!--
Application Skills {#skills}
--------------------------------------------------------------------------------

```{r}
CV %>% print_skill_bars()
```
-->



Disclaimer {#disclaimer}
--------------------------------------------------------------------------------

Made with the R package [**pagedown**](https://github.com/rstudio/pagedown). 

The source code is available [on github.com/nstrayer/cv](https://github.com/nstrayer/datadrivencv).

Last updated on `r Sys.Date()`.



Main
================================================================================

Matthew McClellan {#title}
--------------------------------------------------------------------------------

<!--
```{r}
# Note the special double pipe so we modify the CV object in place
CV %<>% print_text_block("intro") 
```
-->


Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('education')
```




::: aside
```{r}

CV %<>% print_text_block('education_aside')
```
:::

Teaching Experience {data-icon=chalkboard-teacher}
--------------------------------------------------------------------------------

::: aside
```{r}
CV %<>% print_text_block('teaching_experience_aside')
```
:::


```{r}
CV %<>% print_section('teaching_experience')
```


::: aside
```{r}
CV %<>% print_text_block('acc_experience_aside')
```
:::

Other Experience {data-icon=suitcase}
--------------------------------------------------------------------------------
<!--
::: aside
```{r}
CV %<>% print_text_block('other_experience_aside')
```
:::
-->



```{r}
CV %<>% print_section('other_experience')
```

::: aside
```{r}
CV %<>% print_text_block('writing_aside')
```
:::

<!-- These breaks just force a new page so section doesnt get cut off -->


<!-- Selected Writing {data-icon=chart-line}
--------------------------------------------------------------------------------
-->

<!--
```{r}
##CV %<>% print_section('writing')
```

-->



```{r}
CV %<>% print_links()
```
